### ISSUE TITLE
Problem with running ROMs with improper names

### ISSUE THREAD

**Issue by danijel3** [deepmind/xitari#1]
This bug is regarding the DQN demo provided [here](https://sites.google.com/a/deepmind.com/dqn/).

There is an undocumented and undisplayed error in the code that should be addressed. If an improper name of the ROM is used (for example "Breakout" instead of "breakout"), the program simply crashes with a SEGFAULT leaving the user clueless of what they are doing wrong.

The problem is caused by the buildRomRLWrapper function within the games/Roms.cpp file, where the loop is looking through a list of supported ROMs. If the name isn't matched exactly, the method silently returns NULL, causing a crash down the road.

Here are a couple of proposed solutions:
1. Make a note in the README files about the list of supported ROMs and their proper naming convention
2. If possible, make the program output a warning inside the buildRomRLWrapper function before the NULL is returned. Say something like "The ROM  XXX isn't supported. Please make sure the name is written correctly!"
3. Fix this entirely, by asking the user to provide the codename (or some kind of ID) of the game, together with the ROM file, instead of relying on the file name itself - which is a poor practice.
4. Use md5sum in a hashmap to determine which game ROM it is that you are trying to load

**Comment by ghost** [comment]
try using lower case
